name: new-jobs

on: [push]

jobs:
 
  job1:
  
    runs-on: ubuntu-latest

    steps: 

    - run: ls -a
    - name: Checkout
      uses: actions/checkout@v2.5.0 # Default repo to clone down / checkout is our one
    - run: echo '${{github.repository}}'
    - run: ls -a
    
    # Command to print out the contents of a file
    - run: mkdir > new-directory
    - run: cat > new-file.txt
    - run: python hello.py
  
  job2:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo 'Hello World'
    - run: pwd
    - run: ls -a
    - run: echo 'Commit message ${{ github.event.head_commit.message }}'
    - run: echo 'job name ${{ github.job }}'
    
  job3:
    
    
  print_job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -a
